
# Site settings
title:              Ravi Pandya
email:              ravipandya@gmail.com
bio:                Project Manager, Cloud Engineer
description:        Ravi Pandya is a Cloud Engineer, Project Manager, Music Enthusiast, and Web Noodler living and working in San Jose.
baseurl:            "/"
url:                "http://rspandya.github.io"

logo:               'images/logo.png'
#background:         'images/placeholder-big.jpg'
tiled_bg:           false
locale:             en_US

# Jekyll
permalink:          /blog/:year/:month/:day/:title
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   rspandya

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            ravipandya1229@gmail.com
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
email:          ravipandya1229@gmail.com
twitter:        ravipandya
github:         rspandya
stackoverflow:  6327093/rspandya
linkedin:       ravipandya
hackernews:     rspandya

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
